---
kind: pipeline
type: docker
name: go-add

platform:
  os: linux
  arch: amd64



steps:
- name: build
  image: golang:1.13
  commands:
    - go build

- name: test
  image: golang:1.13
  commands:
  - go test -v ./...
