kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test
  when:
    branch:
      - dev

- name: build
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go build

- name: deploy
  image: appleboy/drone-ssh
  volumes:
    - name: key
      path: /root/.ssh/id_rsa
  settings:
    host: 10.159.5.115
    ssh_username: root
    ssh_password: password
    port: 9654
    key_path: /root/.ssh/id_rsa
    script:
      - echo hello
      - echo world
      - cd /home/

volumes:
- name: deps
  temp: {}
- name: key
  host:
    path: /root/.ssh/id_rsa


