kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test
  when:
    branch:
      - dev

- name: build
  image: golang2
  volumes:
  - name: deps
    path: /go
  commands:
  - go build

volumes:
- name: deps
  temp: {}


