kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test
  when:
    branch:
      - dev

- name: build
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go build

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 127.0.0.1
    username:
      from_secret: docker_account
    password:
      from_secret: docker_password
    port: 9654
    key_path: ~/.ssh/id_rsa
    script:
      - echo hello
      - echo world
      - cd /home/

volumes:
- name: deps
  temp: {}


